from tkinter import *
import tkinter.messagebox as mb
class App(Tk):
    def __init__(self):
        super().__init__()
        mi_menu=Menu(self)
        self.geometry("250x350")
        self.config(menu=mi_menu)
        op_menu=Menu(mi_menu,tearoff=0)
        mi_menu.add_cascade(label='Atrás')
        self.l=Label(self,text="Menú")
        self.l.pack(side=TOP)
        frame01 = Frame(self,width=15, height=15)
        frame01.pack(fill= X, padx=1, pady = 1)
        frame1 = Button(self,width=100, height=100)
        frame1.pack(fill= X, padx=1, pady = 1)
        self.l1=Label(frame1,text="Frases ☊")
        self.l1.pack(side=BOTTOM)
        frame12 = Frame(self,width=15, height=15)
        frame12.pack(fill= X, padx=1, pady = 1)

        frame2 = Button(self,width=100, height=100)
        frame2.pack(fill= X, padx=1, pady = 1)
        self.l2=Label(frame2,text="Teclado ⌨")
        self.l2.pack(side=BOTTOM)
        frame23 = Frame(self,width=15, height=15)
        frame23.pack(fill= X, padx=1, pady = 1)
        frame3 = Button(self,width=100, height=100)
        frame3.pack(fill= X, padx=1, pady = 1)
        self.l3=Label(frame3,text="Mensajes ✍")
        self.l3.pack(side=BOTTOM)
        frame34 = Frame(self,width=15, height=15)
        frame34.pack(fill= X, padx=1, pady = 1)
        frame4 = Button(self,width=100, height=100)
        frame4.pack(fill= X, padx=1, pady = 1)
        self.l4=Label(frame4,text="Perfil 👨")
        self.l4.pack(side=BOTTOM)
        frame45 = Frame(self,width=15, height=15)
        frame45.pack(fill= X, padx=1, pady = 1)
        frame5 = Button(self,width=100, height=100)
        frame5.pack(fill= X, padx=1, pady = 1)
        self.l5=Label(frame5,text="Ajustes ⛏")
        self.l5.pack(side=BOTTOM)

if __name__ == "__main__":
    app= App()
    app.mainloop()
