from tkinter import *
import tkinter.messagebox as mb
class App(Tk):
    def __init__(self):
        super().__init__()
        mi_menu=Menu(self)
        self.geometry("200x150")
        frame0 = Frame(self,width=100, height=100)
        frame0.pack(fill= X, padx=20, pady = 1)
        self.e1=Entry(frame0,width=17)
        self.e1.grid(row=0,column=1)
        self.button = Button(frame0, text='Buscar')
        self.button.grid(row=0,column=2)
        frame1 = Frame(self,width=100, height=100)
        frame1.pack(fill= X, padx=1, pady = 1)
        self.buttonq = Button(frame1, text='Q')
        self.buttonq.grid(row=1,column=0)
        self.buttonw = Button(frame1, text='W')
        self.buttonw.grid(row=1,column=1)
        self.buttone = Button(frame1, text='E')
        self.buttone.grid(row=1,column=2)
        self.buttonr = Button(frame1, text='R')
        self.buttonr.grid(row=1,column=3)
        self.buttont = Button(frame1, text='T')
        self.buttont.grid(row=1,column=4)
        self.buttony = Button(frame1, text='Y')
        self.buttony.grid(row=1,column=5)
        self.buttonu = Button(frame1, text='U')
        self.buttonu.grid(row=1,column=6)
        self.buttoni = Button(frame1, text='I')
        self.buttoni.grid(row=1,column=7)
        self.buttono = Button(frame1, text='O')
        self.buttono.grid(row=1,column=8)
        self.buttonp = Button(frame1, text='P')
        self.buttonp.grid(row=1,column=9)
        frame2 = Frame(self,width=100, height=100)
        frame2.pack(fill= X, padx=12, pady = 1)
        self.buttona = Button(frame2, text='A')
        self.buttona.grid(row=0,column=0)
        self.buttons = Button(frame2, text='S')
        self.buttons.grid(row=0,column=1)
        self.buttond = Button(frame2, text='D')
        self.buttond.grid(row=0,column=2)
        self.buttonf = Button(frame2, text='F')
        self.buttonf.grid(row=0,column=3)
        self.buttong = Button(frame2, text='G')
        self.buttong.grid(row=0,column=4)
        self.buttonh = Button(frame2, text='H')
        self.buttonh.grid(row=0,column=5)
        self.buttonj = Button(frame2, text='J')
        self.buttonj.grid(row=0,column=6)
        self.buttonk = Button(frame2, text='K')
        self.buttonk.grid(row=0,column=7)
        self.buttonl = Button(frame2, text='L')
        self.buttonl.grid(row=0,column=8)
        frame3 = Frame(self,width=100, height=100)
        frame3.pack(fill= X, padx=1, pady = 1)
        self.button1= Button(frame3, text='↑')
        self.button1.grid(row=0,column=0)
        self.buttonz= Button(frame3, text='Z')
        self.buttonz.grid(row=0,column=1)
        self.buttonx= Button(frame3, text='X')
        self.buttonx.grid(row=0,column=2)
        self.buttonc= Button(frame3, text='C')
        self.buttonc.grid(row=0,column=3)
        self.buttonv= Button(frame3, text='V')
        self.buttonv.grid(row=0,column=4)
        self.buttonb= Button(frame3, text='B')
        self.buttonb.grid(row=0,column=5)
        self.buttonn= Button(frame3, text='N')
        self.buttonn.grid(row=0,column=6)
        self.buttonm= Button(frame3, text='M')
        self.buttonm.grid(row=0,column=7)
        self.button3= Button(frame3, text='$')
        self.button3.grid(row=0,column=8)
        self.button2= Button(frame3, text='←')
        self.button2.grid(row=0,column=9)
        frame4 = Frame(self,width=100, height=100)
        frame4.pack(fill= X, padx=1, pady = 1)
        self.button4= Button(frame4, text='123')
        self.button4.grid(row=0,column=0)
        self.button5= Button(frame4, text='@')
        self.button5.grid(row=0,column=1)
        self.button6= Button(frame4, text='¥')
        self.button6.grid(row=0,column=2)
        self.buttonesp= Button(frame4, text='    Espacio    ')
        self.buttonesp.grid(row=0,column=3)
        self.buttonret= Button(frame4, text='Return')
        self.buttonret.grid(row=0,column=8)
if __name__ == "__main__":
    app= App()
    app.mainloop()
